### ISSUE TITLE
Can't start superagent-ui container

### ISSUE THREAD

**Issue by Avena83** [superagent-ai/superagent#905]
### Description

Can't start superagent-ui
All another containers working well. Pls help.
`> superagent-ui@0.0.1 supabase:docker:push
> supabase db push --db-url ${SUPABASE_DB_URL}

Connecting to remote database...
Linked project is up to date.

> superagent-ui@0.0.1 start
> next start

[Error: ENOENT: no such file or directory, open '/app/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/.next/BUILD_ID'
}`

### Steps to reproduce

Installed well all containers from great manual. just superagent-ui not working

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@heresandyboy perhaps could Have an answer to this

**Comment by Avena83** [comment]
Totally I solved. On the Dockerfile i add all possible ways to stop to use proxy by npm

# Install production dependencies only
RUN npm config delete proxy
RUN npm config delete http-proxy
RUN npm config delete https-proxy
RUN npm config rm proxy
RUN npm config rm https-proxy
RUN set HTTP_PROXY=null
RUN set HTTPS_PROXY=null
npm set maxsockets 3
.....

Now superagent working! Thanks to me :)
