### ISSUE TITLE
Workflow invoke `outputSchema` should return json and take president over the output schema in SAML 

### ISSUE THREAD

**Issue by homanp** [superagent-ai/superagent#933]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Currently the `outputSchema` doesn't seem to work properly. It does not return JSON when set but a string. Also if outputSchema is sent in the API request it should take president over the the schema in SAML. 

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by elisalimli** [comment]
The output schema passed in request body already has higher presence over the one in the database.

https://github.com/superagent-ai/superagent/blob/main/libs/superagent/app/api/workflows.py#L214-L215
