### ISSUE TITLE
Output parser fails sometimes when output_schema is set. 

### ISSUE THREAD

**Issue by homanp** [superagent-ai/superagent#934]
### Description

Sometimes the langchain output parser complains about parsing issues. A suggestion here is to use a smaller model that can do structured outputs from text instead of the outputparser that is notoriously unreliable. 

### Steps to reproduce

n/a

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by elisalimli** [comment]
@homanp Can you provide some input/output examples that failed in case of you? So I can validate it is fixed.

**Comment by homanp** [comment]
> @homanp Can you provide some input/output examples that failed in case of you? So I can validate it is fixed.

It happens radomly.
