### ISSUE TITLE
Add support for PATCH workflow config

### ISSUE THREAD

**Issue by homanp** [superagent-ai/superagent#945]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A user should be able to update a workflow yaml using the REST API or SDKs. 

Create a new PATCH endpoint for workflowconfigs.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by elisalimli** [comment]
We already do support this.

Unfortunately, we do not support through SDK for now. But users can still use it. 

Here's a Python code example:

```py
import requests
from superagent.client import Superagent
BASE_URL = "https://api.beta.superagent.sh"
API_KEY=""

client = Superagent(
   token=API_KEY,
   base_url=BASE_URL # or your local environment
)


workflow = client.workflow.create(
    request={
        "name": "Bantu Cosmology",
        "description": "Use the African Cosmology to answer any questions",
    }
)


SAML = """ 
workflows:
  - superagent:
      llm: gpt-4-turbo-preview
      name: Browser assistant
      intro: Hi there! How can I help search for answers on the internet.
      prompt: Use the African Cosmology to answer any questions
      superrag:
        - index:
            name: Bantu Cosmology
            urls:
              - https://humana-2.s3.amazonaws.com/African+Cosmology+Bantu+Kongo.pdf
            use_for: Answering questions about African Cosmology
            interpreter_mode: false
            database_provider: qdrant 
"""
requests.post(
    f"{BASE_URL}/api/v1/workflows/{workflow.data.id}/config",
    headers={
        "Content-Type": "application/x-yaml",
        "Authorization": f"Bearer {API_KEY}",
    },
    data=SAML,
).json()    
```
