### ISSUE TITLE
Installation Error - supabase: not found

### ISSUE THREAD

**Issue by taylor-schneider** [superagent-ai/superagent#953]
### Description

I cloned the repo and checked out v0.2.28. When I try to follow the [installation instructions using docker compose](https://docs.superagent.sh/overview/installation/docker-compose) I am unable to get the superagent-ui@0.0.1 image to run. I see the following output in the logs for the container

```
(base) [root@fedora .docker]# docker logs -f superagent-ui

> superagent-ui@0.0.1 supabase:docker:push
> supabase db push --db-url ${SUPABASE_DB_URL}

sh: 1: supabase: not found
(base) [root@fedora .docker]# docker exec -ti superagent-ui /bin/bash
Error response from daemon: Container b89a6228b3a81118eb2b2a7eb5e824768425b7964f660868cf5ce04b0c6a3849 is not running
```

### Steps to reproduce

1. Clone repo 
2. Checked out v0.2.28
3. Configure the hosts file
4. Follow the instructions to deploy supabase, langfuse, vector store
5. Follow the instructions to deploy superagent (i.e. invoke run.sh)

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by suyashSax** [comment]
Ran into the same issue and fixed it by going by adding `npx` before the `supabase` commands in `libs/ui/package.json` like:
```
    "supabase:local:start": "npx supabase start && supabase status",
    "supabase:local:migrate": "npx supabase migrations up",
    "supabase:cloud:login": "npx supabase login",
    "supabase:cloud:link": "npx supabase link",
    "supabase:cloud:push": "npxsupabase db push",
    "supabase:docker:push": "npx supabase db push --db-url ${SUPABASE_DB_URL}",
```

**Comment by taylor-schneider** [comment]
@suyashSax that resolved the issue. I will submit a PR with the fix
