### ISSUE TITLE
Updating LLM in Superagent UI doesn't work properly

### ISSUE THREAD

**Issue by homanp** [superagent-ai/superagent#954]
### Description

Users have identified issues with updating LLM API keys from the Superagnet UI. The underlying issue is that Agents AgentLLM model can have dependencies to older LLM objects. This must be mitigated some how. 

### Steps to reproduce

1. Add a new LLM
2. Update the LLM

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@elisalimli please have a look at this ASAP.

**Comment by elisalimli** [comment]
@homanp Probably this issue happens, because the user has configured same LLM provider through both UI and SDK/Rest API. I came up with a solution in #961 by patching all the given LLM provider has been created so far.
